volumes:
    pg-data:

services:
    db:
        container_name: db
        image: postgres:14
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - path: ./db/.env

    attendance:
        container_name: attendance
        working_dir: /usr/src/app/
        build:
            dockerfile: Dockerfile
            context: .
            args:
                - NODE_ENV=production
        volumes:
            - ./db/.env:/usr/src/app/db/.env
        ports:
            - 5000:5000
        depends_on:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"
